### PR TITLE
add CircleLinux rpm and mannul build support

### PR DESCRIPTION
**Pull request by bella485**

### CODE REVIEW

**Review by cfc4n — COMMENTED** [review]
@xjas  could you review this PR？

**Comment by cfc4n** [comment]
How can we notify you if the spec file changes?

**Comment by bella485** [comment]
> How can we notify you if the spec file changes?

We will check ecapture upstream updates.
Also 也可以在微信群或者email 通知

**Comment by bella485** [comment]
CircleLinux 8.7 we tested:
rpmbuild/RPMS/x86_64/ecapture-0.5.0-1.el8.x86_64.rpm
rpmbuild/SRPMS/ecapture-0.5.0-1.el8.src.rpm
CircleLinux 89.1 we tested:
/home/cc9/rpmbuild/SRPMS/ecapture-0.5.0-1.el9.src.rpm
/home/cc9/rpmbuild/RPMS/x86_64/ecapture-0.5.0-1.el9.x86_64.rpm

**Comment by bella485** [comment]
- Local Build & Test Step
```
git clone https://github.com/bella485/ecapture.git
cd ecapture/builder/
dnf builddep rpmBuild.spec
./rpm_build.sh
```

- On Circle Linux 8
`rpm -ivh ~/rpmbuild/RPMS/x86_64/ecapture-0.5.0-1.el8.x86_64.rpm`

- On Circle Linux 9
```
rpm -ivh ~/rpmbuild/RPMS/x86_64/ecapture-0.5.0-1.el9.x86_64.rpm
ecapture --help
```

**Pull request merged**
