### PR TITLE
kern: support uid/pid filter in ebpf TC hook.

### PR DESCRIPTION
**Pull request by cfc4n**
remove uid/pid filter in kprobe/tcp_sendmsg.

tcp_sendmsg hook all processes are monitored, so there is no need to filter pid and uid, otherwise pid\uid cannot be used in the TC capture_packets function to filter network packets

### CODE REVIEW

**Comment by cfc4n** [comment]
@xxxxxliil try it.

**Comment by xxxxxliil** [comment]
> @xxxxxliil try it.

fix #602 and #605?

**Comment by cfc4n** [comment]
> > @xxxxxliil try it.
> 
> fix #602 and #605?

Yes, there are three issues in these two tickets: 

1. The error message indicates the Hook type is for Golang. 
2. There is no support for filtering network packets by uid. 
3. conn_id is undefined. 

Among them, issue 1 involves incorrect character output but does not actually affect the program logic. Issue 3 was fixed by removing related logs that had no value. The main focus was on fixing issue 2.

**Comment by xxxxxliil** [comment]
#605 fixed
#602 I can't build android target

**Comment by cfc4n** [comment]
`ANDROID=1 make`

**Comment by xxxxxliil** [comment]
> `ANDROID=1 make`

此处的不能构建不是不知道构建命令，而是发行版不能提供对应的 aarch64 头文件（包 aarch64-linux-gnu-linux-api-headers 没有提供 `kconfig.h`）

**Comment by cfc4n** [comment]
我本地做了测试，是可以构建ANDROID的。 如果你在amd64上，也是可以编译x86_64的ANDROID程序。

如果你想交叉编译，那么你需要参考 https://github.com/gojue/ecapture/blob/master/.github/workflows/release.yml#L27 ，下载头文件源码，并构建生成相关头文件。 在makefile时引用。


另外：因为你不是ubuntu，无法使用已经提供好的脚本。所以，你需要手动安装。

**Pull request merged**
