### PR TITLE
feat: remove tcp packet limitation

### PR DESCRIPTION
**Pull request by yuweizzz**
remove tcp packet limitation, allow capture udp/quic packet.

### CODE REVIEW

**Comment by cfc4n** [comment]
Can you upload a pcapng file captured by `ecapture` of the QUIC protocol? I would like to know if `Wireshark` supports TLS decryption for `QUIC`.

**Comment by yuweizzz** [comment]
Check this:
[save.zip](https://github.com/user-attachments/files/17000672/save.zip)

**Comment by cfc4n** [comment]
cc_snip_2024-09-15_14-20-37

OK, eCapture works.

**Review by cfc4n — APPROVED** [review]
LGTM

**Pull request merged**
