### PR TITLE
Fix cant found RET offset in gotls mode. fix #502.

### LINKED ISSUE #502: ecapture 0.7.6依旧无法抓取docker pull的完全URL
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Linux Server/Android (please complete the following information):**

- Env: [run `make env` to get the environment variables]
- OS: [e.g. Ubuntu 21.04]
- Arch: [e.g. arm_aarch64]
- Kernel Version: [e.g. 5.10]
- Version: [e.g. 0.1.3-20220313-69c1e0]

**Additional context**

ecapture gotls --elfpath=/usr/bin/docker --hex; 

docker pull redis ;

### PR DESCRIPTION
**Pull request by cfc4n**
Fix the issue of not being able to fetch the function RET offset in the gotls model when building a Golang binary with pie mode.

```shell
GO_BUILDMODE="-buildmode=pie"
```

ref: https://github.com/docker/cli/blob/799bf5268039a92c9af197abd612b0f36cf9efe1/scripts/build/.variables#L75C13-L75C42

Here, a constant `IdaProOffset = 0x120` is used. I found through IDA static symbol analysis that the address of `crypto/tls.(*Conn).Read` is `46EE50`. The address calculated by the program is always `0x120` less than this number. By analyzing multiple compiled programs, I found that the difference is always `0x120`. Therefore, I defined a constant and added it to the address calculated by the program. However, I don't know the reason, if you know, please let me know.

----
这里，使用了一个常量`IdaProOffset = 0x120`，我是通过IDA静态分析符号发现`crypto/tls.(*Conn).Read`的地址是`46EE50`，我用程序计算出来的总是比这个数字少了`0x120` ，通过分析其他多个编译的程序，发现差值总是`0x120`，所以，我定义了一个常量，增加到程序计算的地址上。但是我不知道原因，如果你知道，请告诉我。

```golang
func (gc *GoTLSConfig) findPieSymbolAddr(lfunc string) (uint64, error) {
	f := gc.goSymTab.LookupFunc(lfunc)
	if f == nil {
		return 0, errors.New("Cant found symbol address on pie model.")
		// f.Value - prog.Vaddr + prog.Off + IdaProOffset
	}
	var err error
	var address uint64
	for _, prog := range gc.goElf.Progs {
		if prog.Type != elf.PT_LOAD || (prog.Flags&elf.PF_X) == 0 {
			continue
		}
		// For more info on this calculation: stackoverflow.com/a/40249502
		address = f.Value
		if prog.Vaddr <= f.Value && f.Value < (prog.Vaddr+prog.Memsz) {
			funcLen := f.End - f.Entry
			data := make([]byte, funcLen)
			address = f.Value - prog.Vaddr + prog.Off + IdaProOffset
			_, err = prog.ReadAt(data, int64(address))
			if err != nil {
				return 0, fmt.Errorf("search function return: %w", err)
			}
			return address, nil
		}
	}
	return 0, ErrorNoRetFoundFromSymTabFun
}
```

cc_snip_2024-03-30_17-38-52

### CODE REVIEW

**Comment by sancppp** [comment]
Why do I get a `could not find magic number` error in my test environment?

As you can see in the picture, my order of operation is right before left.
CleanShot_2024-03-24_at_20 00 50@2x

**Comment by cfc4n** [comment]
is `tests`  not a ELF file?  The pie mode requires enabling CGO.

please use command :
```shell
CGO_ENABLED=1 go build -buildmode=pie  -o test main.go
```


ps: 
This PR is not yet complete, I am in the process of optimizing it.

**Comment by sancppp** [comment]
> is `tests` not a ELF file? The pie mode requires enabling CGO.
> 
> please use command :
> 
> ```shell
> CGO_ENABLED=1 go build -buildmode=pie  -o test main.go
> ```
> 
> ps: This PR is not yet complete, I am in the process of optimizing it.

It looks the same as before.

CleanShot_2024-03-24_at_20 31 09@2x

I'm going to wait until this PR is complete before I run these tests, in order to understand what's changed in this PR.

**Review by cfc4n — COMMENTED** [review]
reviewed.

**Review by sancppp — APPROVED** [review]

**Pull request merged**
